language: python

env:
  - DJANGO=1.9.1
  - DJANGO_SETTINGS_MODULE="dj_blog.settings"
  - PYTHONPATH="/home/sotnyk/.virtualenvs/dj_blog"

python:
    - 3.4

install: "pip install -r requirements.txt"

script:
  - python manage.py runserver