# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161008_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
